apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: synergy-crm

spec:
  instances: 11

  imageName: ghcr.io/cloudnative-pg/postgresql:17

  storage:
    size: 5Gi

  bootstrap:
    initdb:
      database: synergy_db
      owner: admin
      secret:
        name: synergy-secrets
