resources:
  - namespace.yaml
  - secrets.yaml
  - db-postgres.yaml
  - db-mongo.yaml
  - db-redis.yaml
  - auth-service.yaml
  - crm-service.yaml
  - inventory-service.yaml
  - sales-service.yaml
  - frontend.yaml
  - ingress.yaml
