apiVersion: v1
kind: Secret
metadata:
  name: postgres-cluster-secret
  namespace: inventory-prod
type: kubernetes.io/basic-auth
stringData:
  username: "<SET_IN_PRODUCTION>"
  password: "<SET_IN_PRODUCTION>"
