apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: inventory-prod

spec:
  instances: 6

  imageName: ghcr.io/cloudnative-pg/postgresql:17

  storage:
    size: 10Gi

  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

  bootstrap:
    initdb:
      database: inventory_db
      owner: admin
      secret:
        name: postgres-cluster-secret

  postgresql:
    parameters:
      max_wal_senders: "32"
      max_replication_slots: "32"
      wal_level: "logical"
      wal_keep_size: "512MB"
      max_connections: "200"
