apiVersion: v1
kind: Secret
metadata:
  name: synergy-secrets
  namespace: synergy-crm
type: Opaque
stringData:
  postgres-user: admin
  postgres-password: SuperSecurePassword123
  postgres-db: inventory_db
  mongo-uri: mongodb://mongo-db:27017/inventory_db
  redis-url: redis://redis-cache:6379/0
