"""Add description to permissions

Revision ID: 4409a85da3fb
Revises: 1674c956111c
Create Date: 2026-07-06 13:38:25.239482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4409a85da3fb'
down_revision: Union[str, Sequence[str], None] = '1674c956111c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'description')
    # ### end Alembic commands ###
