"""extend_leads_for_crm_pipeline

Revision ID: 89132dc3003e
Revises: ba250b071a00
Create Date: 2026-07-16 11:07:35.127985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89132dc3003e'
down_revision: Union[str, Sequence[str], None] = 'ba250b071a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('stage', sa.String(length=50), nullable=False))
    op.add_column('leads', sa.Column('demo_status', sa.String(length=50), nullable=False))
    op.add_column('leads', sa.Column('requirements', sa.String(length=1000), nullable=True))
    op.add_column('leads', sa.Column('quotation_type', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('quotation_items', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'quotation_items')
    op.drop_column('leads', 'quotation_type')
    op.drop_column('leads', 'requirements')
    op.drop_column('leads', 'demo_status')
    op.drop_column('leads', 'stage')
    # ### end Alembic commands ###
